// -->myioctl.h
/* Use 'p' as magic number */
#define LOGIBONE_FIFO_IOC_MAGIC 'p'
/* Please use a different 8-bit number in your code */
#define LOGIBONE_FIFO_RESET _IO(LOGIBONE_FIFO_IOC_MAGIC, 0)
#define MAX_STRING_SIZE 128 

#define LOGIBONE_FIFO_PEEK _IOR(LOGIBONE_FIFO_IOC_MAGIC, 1, short)
#define LOGIBONE_FIFO_NB_FREE _IOR(LOGIBONE_FIFO_IOC_MAGIC, 2, short)
#define LOGIBONE_FIFO_NB_AVAILABLE _IOR(LOGIBONE_FIFO_IOC_MAGIC, 3, short)
#define LOGIBONE_FIFO_MODE _IO(LOGIBONE_FIFO_IOC_MAGIC, 4)
#define LOGIBONE_DIRECT_MODE _IO(LOGIBONE_FIFO_IOC_MAGIC, 5)
#define FPGA_LEDR _IO(LOGIBONE_FIFO_IOC_MAGIC, 6 )
#define FPGA_LEDG _IO(LOGIBONE_FIFO_IOC_MAGIC, 7 )
#define FPGA_HEX0 _IO(LOGIBONE_FIFO_IOC_MAGIC, 8 )
#define FPGA_HEX1 _IO(LOGIBONE_FIFO_IOC_MAGIC, 9 )
#define FPGA_HEX2 _IO(LOGIBONE_FIFO_IOC_MAGIC, 10 )
#define FPGA_HEX3 _IO(LOGIBONE_FIFO_IOC_MAGIC, 11 )
#define FPGA_HEX4 _IO(LOGIBONE_FIFO_IOC_MAGIC, 12 )
#define FPGA_HEX5 _IO(LOGIBONE_FIFO_IOC_MAGIC, 13 )
#define FPGA_HEX6 _IO(LOGIBONE_FIFO_IOC_MAGIC, 14 )
#define FPGA_HEX7 _IO(LOGIBONE_FIFO_IOC_MAGIC, 15 )
#define FPGA_SRAM_W _IO(LOGIBONE_FIFO_IOC_MAGIC, 16 )
#define FPGA_ENSRAM _IO(LOGIBONE_FIFO_IOC_MAGIC, 17 )
#define FPGA_SRAM_R _IO(LOGIBONE_FIFO_IOC_MAGIC, 18 )
#define ENAUDIO _IO (LOGIBONE_FIFO_IOC_MAGIC, 19)
#define INT_PID _IO(LOGIBONE_FIFO_IOC_MAGIC, 20 )
#define CPU_ACK _IO(LOGIBONE_FIFO_IOC_MAGIC, 21 )
#define BASE_ADDR_WR _IO(LOGIBONE_FIFO_IOC_MAGIC, 22)
#define BASE_ADDR_RD _IO(LOGIBONE_FIFO_IOC_MAGIC, 23)
#define ENTIMER _IO(LOGIBONE_FIFO_IOC_MAGIC, 24)
#define SETTIMER _IO(LOGIBONE_FIFO_IOC_MAGIC, 25)
#define FPGA_SRAM_CLEAR _IO(LOGIBONE_FIFO_IOC_MAGIC, 26)


#define FPGA_LEDG0 _IO(LOGIBONE_FIFO_IOC_MAGIC, 29)
#define FPGA_LEDG1 _IO(LOGIBONE_FIFO_IOC_MAGIC, 30)
#define FPGA_LEDG2 _IO(LOGIBONE_FIFO_IOC_MAGIC, 31)
#define FPGA_LEDG3 _IO(LOGIBONE_FIFO_IOC_MAGIC, 32)
#define FPGA_LEDG4 _IO(LOGIBONE_FIFO_IOC_MAGIC, 33)
#define FPGA_LEDG5 _IO(LOGIBONE_FIFO_IOC_MAGIC, 34)
#define FPGA_LEDG6 _IO(LOGIBONE_FIFO_IOC_MAGIC, 35)
#define FPGA_LEDG7 _IO(LOGIBONE_FIFO_IOC_MAGIC, 36)
#define FPGA_LEDR0 _IO(LOGIBONE_FIFO_IOC_MAGIC, 37)
#define FPGA_LEDR1 _IO(LOGIBONE_FIFO_IOC_MAGIC, 38)
#define FPGA_LEDR2 _IO(LOGIBONE_FIFO_IOC_MAGIC, 39)
#define FPGA_LEDR3 _IO(LOGIBONE_FIFO_IOC_MAGIC, 40)
#define FPGA_LEDR4 _IO(LOGIBONE_FIFO_IOC_MAGIC, 41)
#define FPGA_LEDR5 _IO(LOGIBONE_FIFO_IOC_MAGIC, 42)
#define FPGA_LEDR6 _IO(LOGIBONE_FIFO_IOC_MAGIC, 43)
#define FPGA_LEDR7 _IO(LOGIBONE_FIFO_IOC_MAGIC, 44)
#define FPGA_LEDR8 _IO(LOGIBONE_FIFO_IOC_MAGIC, 45)
#define FPGA_LEDR9 _IO(LOGIBONE_FIFO_IOC_MAGIC, 46)
#define FPGA_LEDR10 _IO(LOGIBONE_FIFO_IOC_MAGIC, 47)
#define FPGA_LEDR11 _IO(LOGIBONE_FIFO_IOC_MAGIC, 48)
#define FPGA_LEDR12 _IO(LOGIBONE_FIFO_IOC_MAGIC, 49)
#define FPGA_LEDR13 _IO(LOGIBONE_FIFO_IOC_MAGIC, 50)
#define FPGA_LEDR14 _IO(LOGIBONE_FIFO_IOC_MAGIC, 51)
#define FPGA_LEDR15 _IO(LOGIBONE_FIFO_IOC_MAGIC, 52)
#define FPGA_LCD0 _IO(LOGIBONE_FIFO_IOC_MAGIC, 53)
#define FPGA_LCD1 _IO(LOGIBONE_FIFO_IOC_MAGIC, 54)
#define FPGA_LCD2 _IO(LOGIBONE_FIFO_IOC_MAGIC, 55)
#define FPGA_LCD3 _IO(LOGIBONE_FIFO_IOC_MAGIC, 56)
#define FPGA_LCD4 _IO(LOGIBONE_FIFO_IOC_MAGIC, 57)
#define FPGA_LCD5 _IO(LOGIBONE_FIFO_IOC_MAGIC, 58)
#define FPGA_LCD6 _IO(LOGIBONE_FIFO_IOC_MAGIC, 59)
#define FPGA_LCD7 _IO(LOGIBONE_FIFO_IOC_MAGIC, 60)
#define FPGA_LCD8 _IO(LOGIBONE_FIFO_IOC_MAGIC, 61)
#define FPGA_LCD9 _IO(LOGIBONE_FIFO_IOC_MAGIC, 62)
#define FPGA_LCD10 _IO(LOGIBONE_FIFO_IOC_MAGIC, 63)
#define FPGA_LCD11 _IO(LOGIBONE_FIFO_IOC_MAGIC, 64)
#define FPGA_LCD12 _IO(LOGIBONE_FIFO_IOC_MAGIC, 65)
#define FPGA_LCD13 _IO(LOGIBONE_FIFO_IOC_MAGIC, 66)
#define FPGA_LCD14 _IO(LOGIBONE_FIFO_IOC_MAGIC, 67)
#define FPGA_LCD15 _IO(LOGIBONE_FIFO_IOC_MAGIC, 68)
#define FPGA_LCD16 _IO(LOGIBONE_FIFO_IOC_MAGIC, 69)
#define FPGA_LCD17 _IO(LOGIBONE_FIFO_IOC_MAGIC, 70)
#define FPGA_LCD18 _IO(LOGIBONE_FIFO_IOC_MAGIC, 71)
#define FPGA_LCD19 _IO(LOGIBONE_FIFO_IOC_MAGIC, 72)
#define FPGA_LCD20 _IO(LOGIBONE_FIFO_IOC_MAGIC, 73)
#define FPGA_LCD21 _IO(LOGIBONE_FIFO_IOC_MAGIC, 74)
#define FPGA_LCD22 _IO(LOGIBONE_FIFO_IOC_MAGIC, 75)
#define FPGA_LCD23 _IO(LOGIBONE_FIFO_IOC_MAGIC, 76)
#define FPGA_LCD24 _IO(LOGIBONE_FIFO_IOC_MAGIC, 77)
#define FPGA_LCD25 _IO(LOGIBONE_FIFO_IOC_MAGIC, 78)
#define FPGA_LCD26 _IO(LOGIBONE_FIFO_IOC_MAGIC, 79)
#define FPGA_LCD27 _IO(LOGIBONE_FIFO_IOC_MAGIC, 80)
#define FPGA_LCD28 _IO(LOGIBONE_FIFO_IOC_MAGIC, 81)
#define FPGA_LCD29 _IO(LOGIBONE_FIFO_IOC_MAGIC, 82)
#define FPGA_LCD30 _IO(LOGIBONE_FIFO_IOC_MAGIC, 83)
#define FPGA_LCD31 _IO(LOGIBONE_FIFO_IOC_MAGIC, 84)
#define FPGA_LCDREF _IO(LOGIBONE_FIFO_IOC_MAGIC, 85)
#define FPGA_VERSION _IO(LOGIBONE_FIFO_IOC_MAGIC, 86)

#define SEG_1 0x06
#define SEG_2 0x5B
#define SEG_3 0x4F
#define SEG_4 0x66
#define SEG_5 0x6D
#define SEG_6 0x7D
#define SEG_7 0x07
#define SEG_8 0x7F
#define SEG_9 0x67
#define SEG_0 0x3F

#define LCD_A 0x41
#define LCD_B 0x42
#define LCD_C 0x43
#define LCD_D 0x44
#define LCD_E 0x45
#define LCD_F 0x46
#define LCD_G 0x47
#define LCD_H 0x48
#define LCD_I 0x49
#define LCD_J 0x4A
#define LCD_K 0x4B
#define LCD_L 0x4C
#define LCD_M 0x4D
#define LCD_N 0x4E
#define LCD_O 0x4F
#define LCD_P 0x50
#define LCD_Q 0x51
#define LCD_R 0x52
#define LCD_S 0x53
#define LCD_T 0x54
#define LCD_U 0x55
#define LCD_V 0x56
#define LCD_W 0x57
#define LCD_X 0x58
#define LCD_Y 0x59
#define LCD_Z 0x5A


#define INT_SIG 44 

#define FPGA_LEDGBASE 32 //green led base address to FPGA 
#define FPGA_LEDRBASE 48 //red led base address to FPGA
#define FPGA_LCDBASE 84 //lcd display base address to FPGA
#define FPGA_VBASE 256 //FPGA version base address


#define ENAUDIORD 1
#define DISAUDIORD 0 


